# Aluno: IGE111111 - Joao Nicolau
name: Qodana Feature Envy Detection

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        with:
          # Define o "Quality Gate" para falhar se encontrar instâncias
          args: --fail-threshold,1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}