#122477 - Maria Frade

name: Qodana Code Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  qodana:
    name: Qodana Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2023.3
        with:
          linter: jetbrains/qodana-jvm
          args: --fail-threshold 1

      - name: Upload Qodana report
        uses: actions/upload-artifact@v4
        with:
          name: qodana-report
          path: qodana-report

  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_122477 }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=maria-frade_asasdad \
          -Dsonar.organization=Maria Frade